export const GET_FAVOURITE_MOVIES_REQUEST = "GET_FAVOURITE_MOVIES_REQUEST";
export const GET_FAVOURITE_MOVIES_SUCCESS = "GET_FAVOURITE_MOVIES_SUCCESS";
export const GET_FAVOURITE_MOVIES_ERROR = "GET_FAVOURITE_MOVIES_ERROR";
export const REMOVE_FAVOURITE_MOVIE = "REMOVE_FAVOURITE_MOVIE";
export const ADD_FAVOURITE_MOVIE = "ADD_FAVOURITE_MOVIE";
